kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: ubuntu:latest
    pull: if-not-exists
    commands:
      - apt update && apt install -y iputils-ping
      - ./tracert.sh google.com
